### ISSUE TITLE
Unknown block tag?

### ISSUE THREAD

**Issue by tusamni** [alexmacarthur/jam-comments-javascript#1]
On a new install, I'm getting an "Unknown block tag: jamComments" error.

**Comment by tusamni** [comment]
As a sidenote, if I switch the tag from {% jamComments %} to {% jamcomments %} the error changes to:

```Cannot read property toLowerCase of undefined

**Comment by alexmacarthur** [comment]
Hi, @tusamni - sorry I missed this until now! Correct, the tag name is all lowercase, and you'll also need to have three ENV variables in place: 

JAM_COMMENTS_DOMAIN
JAM_COMMENTS_API_KEY
NODE_ENV (technically this one isn't required to run it locally, but it'll fall back to "development" mode if it's not set)

I did update the package tonight to provide a little bit better error handling... go ahead and upgrade before trying again: 

https://www.npmjs.com/package/@jam-comments/eleventy

This tool is very much still adapting as we lift it off... so please keep sending your feedback!

**Comment by alexmacarthur** [comment]
@tusamni Semi-related... just glanced at your site/blob. 😮 Incredible. Nice job on that.

**Comment by tusamni** [comment]
@alexmacarthur Just another FYI, under the API Key section:

The documentation link here doesn't work:
`You'll need this key in order to successfully publish any comments from your site(s). For help using this API key in setting up JamComments for a site, see the documentation.`

**Comment by alexmacarthur** [comment]
Cool, thanks for the heads up -- got it fixed 👍
