### ISSUE TITLE
require() of ES Module in server-utilities log.js

### ISSUE THREAD

**Issue by jacoballred** [alexmacarthur/jam-comments-javascript#6]
I'm getting a `require() of ES Module` error from log.js when trying to use jam-comments with Astro. It looks like `require("chalk")` needs updated to use an `import`.

**Comment by alexmacarthur** [comment]
Thanks for letting me know, @jacoballred! I'll check it out.

**Comment by alexmacarthur** [comment]
@jacoballred - Great news, issue resolved. Please try v1.0.2 and let me know how everything goes. Thanks again!

**Comment by jacoballred** [comment]
Fantastic, thank you so much! It is working now!
