### ISSUE TITLE
Astro: comments not retrieved from AWS S3 hosted website (http, Bucket name contains www)

### ISSUE THREAD

**Issue by putza** [alexmacarthur/jam-comments-javascript#8]
**Website**: http://www.grandmafak.com.s3-website-us-west-2.amazonaws.com/
Revision:
'@jam-comments/astro':
    specifier: ^1.2.0
    version: 1.2.0(sharp@0.32.5)

### Observed Behaviour:
1) I can sign in and out through the comments plugin on the Astro site
2) I can create a comment 
![image](https://github.com/alexmacarthur/jam-comments-javascript/assets/5171289/f2fd8f15-6178-48d3-88f6-dca490ff6fdb)
3) The comment appears in the JamComments administration backend as "pending". When I reload the page, the comment is gone.
![image](https://github.com/alexmacarthur/jam-comments-javascript/assets/5171289/0d78d814-61c2-489e-9a57-6be97d1d6a47)
3) In the JamComments backend I can approve the comment
4) I reload the page and the comments are empty

### Astro Config:
1) I declared the Domain and API Key and so on as env variable. The comments show up, so I assume this is correct
2) Followd the Astro example in the guide to configure the plugin

### Observations:
1) In the backend I see that the comment path registers as "/" and the link address as https://grandmafak.com.s3-website-us-west-2.amazonaws.com/. However this link address is invalid as S3 does not support https hosting, and the bucket needs the www prefice as in the link on the top of the post.
2) I might try to add a CloudFront https backend. See if that corrects the problem.

**Comment by putza** [comment]
I deployed the website through AWS CloudFront: https://dktnhgwty5uu9.cloudfront.net/

Effect:
1) Backend: The comments show up. The Hyperlinks back to the website work now
2) Website: Comment does not show up after reload.

**Comment by alexmacarthur** [comment]
Hi, @putza - 

It looks like the comment was successfully created in the back end. However, it's required that your site go through a full rebuild before it'll show up rendered in your page's HTML. A reload won't do the trick -- you'll need to rebuild. Let me know if/when you give that a shot.

**Comment by putza** [comment]
Hi @alexmacarthur,

thanks for the quick reply. That worked. So for a full workflow, 
I need to trigger a github action through the webhook in the backend to rebuild and redeploy the site. Will try this out next.

But your comment resolved my problem.
